version: '3.7'
services:
    php:
        # image: 'php:7.2-fpm'
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME:?err}-php
        volumes:
            - './app:/var/www/html'

    nginx:
        image: nginx:latest
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - '${APP_PORT:-80}:80'
        links:
            - 'php'
        volumes:
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'

    # mariadb:
    #     image: mariadb:latest
    #     container_name: ${APP_NAME:?err}-mariadb
    #     restart: 'on-failure'
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
    #     ports:
    #         - '3301:3306'
    #     volumes:
    #         - ${PWD}
volumes:
    dbdata:
